# Generated by Django 5.2.5 on 2025-08-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAssumptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_kwc_solar', models.FloatField(default=1200)),
                ('cost_per_kw_pump', models.FloatField(default=500)),
                ('installation_fees_percent', models.FloatField(default=15)),
                ('maintenance_percent_per_year', models.FloatField(default=1.5)),
                ('cost_per_kwh_grid', models.FloatField(default=0.14)),
                ('cost_per_kwh_diesel', models.FloatField(default=0.45)),
                ('system_lifespan_years', models.IntegerField(default=25)),
                ('discount_rate_percent', models.FloatField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='SolarPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('power_watt', models.IntegerField()),
                ('efficiency', models.FloatField()),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WaterPump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('power_kw', models.FloatField()),
                ('max_flow_rate_m3_h', models.FloatField()),
                ('max_hmt', models.FloatField()),
                ('cost', models.FloatField()),
            ],
        ),
    ]
