# Generated by Django 5.2.5 on 2025-08-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Simulation sans nom', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('volume_eau', models.FloatField()),
                ('hmt', models.FloatField()),
                ('results_json', models.JSONField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
