# Generated by Django 5.2.5 on 2025-08-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_simulationresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('voltage', models.IntegerField()),
                ('capacity_ah', models.IntegerField()),
                ('dod_percent', models.FloatField(default=50)),
                ('efficiency', models.FloatField(default=85)),
                ('cost', models.FloatField()),
            ],
        ),
    ]
